# Generated by Django 3.0.3 on 2021-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210420_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberphone',
            name='phone1',
            field=models.CharField(default='1111111111', max_length=10),
        ),
        migrations.AlterField(
            model_name='memberphone',
            name='phone2',
            field=models.CharField(default='1111111111', max_length=10),
        ),
    ]
