# Generated by Django 3.0.3 on 2021-04-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_member_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone2',
        ),
        migrations.CreateModel(
            name='MemberPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=5)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Member')),
            ],
        ),
    ]
