# Generated by Django 3.0.3 on 2021-04-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '__first__'),
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_no', models.AutoField(primary_key=True, serialize=False)),
                ('plantype', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('cost', models.IntegerField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Guest')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_dtno', models.IntegerField()),
                ('No_adults', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')])),
                ('No_children', models.IntegerField(choices=[(0, '0'), (1, '1')])),
                ('book_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('rno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_type')),
                ('sid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Service_in_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_dtno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking_detail')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='service_in_room',
            constraint=models.UniqueConstraint(fields=('sid', 'book_dtno'), name='unique_together1'),
        ),
        migrations.AddConstraint(
            model_name='booking_detail',
            constraint=models.UniqueConstraint(fields=('book_no', 'book_dtno'), name='unique_together'),
        ),
    ]
