# Generated by Django 3.0.3 on 2021-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210409_2314'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service_in_room',
            name='unique',
        ),
        migrations.AddConstraint(
            model_name='service_in_room',
            constraint=models.UniqueConstraint(fields=('sid', 'book_dtno'), name='unique_together1'),
        ),
    ]
