# Generated by Django 3.0.3 on 2021-04-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20210409_1905'),
        ('booking', '0007_auto_20210420_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='sid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='room.Service'),
        ),
    ]
