# Generated by Django 3.0.3 on 2021-04-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20210409_1905'),
        ('booking', '0008_booking_detail_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='sid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Service'),
        ),
    ]
